-- NetArmor AI - Supabase Schema & Security Setup
-- Execute this entire script in your Supabase SQL Editor.
-- Public registration creates role='user'. Promote associates manually to 'associate'.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  full_name text,
  email text,
  role text not null default 'user' check (role in ('user', 'associate')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scan_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scan_type text not null check (scan_type in ('url', 'email', 'message', 'document')),
  target text not null,
  result text not null check (result in ('Threat', 'Safe')),
  risk_score numeric(5,2) not null check (risk_score >= 0 and risk_score <= 100),
  created_at timestamptz not null default now()
);

-- Establish explicit foreign key link between scan_history and profiles for PostgREST joins
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_scan_history_profiles'
  ) then
    alter table public.scan_history
      add constraint fk_scan_history_profiles
      foreign key (user_id) references public.profiles(id) on delete cascade;
  end if;
end $$;

create index if not exists idx_scan_history_user_created
  on public.scan_history(user_id, created_at desc);

create index if not exists idx_scan_history_created
  on public.scan_history(created_at desc);

-- Automatic Profile Creation Trigger on Auth User Creation
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, email, full_name, role)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'username', ''), split_part(new.email, '@', 1)),
    new.email,
    nullif(new.raw_user_meta_data->>'full_name', ''),
    'user'
  )
  on conflict (id) do update set
    email = excluded.email,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Security Check Helper: Check if current authenticated user has associate privileges
create or replace function public.is_associate()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'associate'
  );
$$;

grant execute on function public.is_associate() to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.scan_history to authenticated;

alter table public.profiles enable row level security;
alter table public.scan_history enable row level security;

-- Policies for public.profiles
drop policy if exists "profiles_select_own_or_associate" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "profiles_associate_update" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;

create policy "profiles_select_own_or_associate"
on public.profiles for select to authenticated
using (id = auth.uid() or public.is_associate());

create policy "profiles_insert_own"
on public.profiles for insert to authenticated
with check (id = auth.uid());

create policy "profiles_update_own"
on public.profiles for update to authenticated
using (id = auth.uid())
with check (id = auth.uid() and role = 'user');

create policy "profiles_associate_update"
on public.profiles for update to authenticated
using (public.is_associate())
with check (public.is_associate());

-- Policies for public.scan_history
drop policy if exists "scan_select_own_or_associate" on public.scan_history;
drop policy if exists "scan_insert_own" on public.scan_history;

create policy "scan_select_own_or_associate"
on public.scan_history for select to authenticated
using (user_id = auth.uid() or public.is_associate());

create policy "scan_insert_own"
on public.scan_history for insert to authenticated
with check (user_id = auth.uid());
